[package]
name = "workflowtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["native-tls","json"]}
tokio = { version = "1.17", features = ["full"] }
