#!/bin/sh
# set -e

# # In case this system is running systemd, we make systemd reload the unit files
# # to pick up changes.
# if [ -d /run/systemd/system ] ; then
# 	systemctl --system daemon-reload >/dev/null || true
# fi

# if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
# 	if [ -x "/usr/bin/deb-systemd-helper" ]; then
# 		deb-systemd-helper purge workflowtest.service >/dev/null || true
# 		deb-systemd-helper unmask workflowtest.service >/dev/null
# 	fi
# fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask workflowtest.service >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge workflowtest.service >/dev/null || true
		deb-systemd-helper unmask workflowtest.service >/dev/null || true
	fi
fi